language: c
sudo: true

os:
  - linux
  - osx
  - windows

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      choco install make;
    elif [[ $TRAVIS_OS_NAME == linux ]]; then
      pip install cmake --upgrade --user;
    fi
  - cmake --version

install:
  - mkdir build
  - cd build
  - if [[ $TRAVIS_OS_NAME != windows ]]; then
      cmake ../src;
    else
      cmake  -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ../src;
    fi
  - cmake --build .

script:
  - echo "Joel all ist gut jetzt wir brauchen dienen Teste"

