language: c
sudo: true

os:
  - linux
  - osx

before_install:
  - sudo apt-get install gfortran
  - |-
      case $TRAVIS_OS_NAME in
        windows)
          choco install make
          ;;
      esac

install:
  - git clone https://github.com/json-c/json-c.git
  - mkdir json-c-build
  - cd json-c-build
  - cmake ../json-c
  - sudo make install
  - cd ..
  - cd src
  - make

script:
  - ./build/test
  - if [[ -f "./build/test" ]]; then
      echo "Joel all ist gut jetzt wir brauchen dienen Teste";
    else
      exit 1;
  - echo
