language: c
sudo: true

os:
  - windows

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      choco install make;
    elif [[ $TRAVIS_OS_NAME == linux ]]; then
      sudo apt-get install gfortran;
    fi

install:
  - if [[ $TRAVIS_OS_NAME != windows ]]; then
      git clone https://github.com/json-c/json-c.git;
      mkdir json-c-build;
      cd json-c-build;
      cmake ../json-c;
      sudo make install;
    else
       git clone https://github.com/Microsoft/vcpkg.git;
       git clone https://github.com/json-c/json-c.git;
       cd vcpkg;
       bootstrap-vcpkg.bat;
       vcpkg integrate install;
       vcpkg install json-c;
    fi
  - cd ..
  - cd src
  - make

script:
  - echo "Joel all ist gut jetzt wir brauchen dienen Teste"

