language: c
sudo: true

os:
  - linux
  - osx
  - windows

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      choco install make;
    elif [[ $TRAVIS_OS_NAME == linux ]]; then
      sudo apt-get install gfortran;
    fi

install:
  - git clone https://github.com/json-c/json-c.git
  - mkdir json-c-build
  - cd json-c-build
  - cmake ../json-c
  - if [[ $TRAVIS_OS_NAME != windows ]]; then
      sudo make install;
    fi
  - cd ..
  - cd src
  - make

script:
  - echo "Joel all ist gut jetzt wir brauchen dienen Teste"

