language: c
sudo: true

os:
  - linux

before_install:
  - sudo apt-get install gfortran
  - |-
      case $TRAVIS_OS_NAME in
        windows)
          choco install make
          ;;
      esac

install:
  - git clone https://github.com/json-c/json-c.git
  - mkdir json-c-build
  - cd json-c-build
  - cmake ../json-c
  - sudo make install
  - cd ..
  - cd test
  - make

script:
  - ./build/hello
  - echo "Joel all ist gut jetzt wir brauchen dienen Teste"
  - exit 1
