image:
  - Visual Studio 2017

build: off

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 3

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%

install:
  - cmd: mkdir build
  - cd build
  - cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ../src
  - sh: cmake ..

  - cmake --build .
