# -*- MakeFile -*-


a: main.o
	gfortran -o a main.o actions.o albedo.o allocate_parms.o \
	animal_herd_module.o aqu2d_init.o aqu2d_read.o aqu_1d_control.o aqu_hyds.o aqu_initial.o \
	aqu_pesticide_module.o aqu_pesticide_output.o aqu_read.o aqu_read_elements.o aqu_read_init.o \
	aquifer_module.o aquifer_output.o ascrv.o atri.o aunif.o basin_aqu_pest_output.o \
	basin_aquifer_output.o basin_ch_pest_output.o basin_chanmorph_output.o basin_channel_output.o \
	basin_ls_pest_output.o basin_module.o basin_output.o basin_print_codes_read.o basin_prm_default.o \
	basin_read_cc.o basin_read_objs.o basin_read_prm.o basin_recall_output.o basin_res_pest_output.o \
	basin_reservoir_output.o basin_sdchannel_output.o cal_allo_init.o ch_watqual_semi_analitical_function.o \
	path_hru_aqu_read.o hru_urban.o overland_n_read.o soiltest_init.o hydrograph_module.o \
	pathogen_data_module.o water_hru.o nut_nitvol.o hydout_output.o reservoir_data_module.o lsu_output.o \
	snowdb_read.o res_read_weir.o pl_grow.o calsoft_read_codes.o ero_pkq.o mgt_sched.o wetland_control.o \
	soil_lte_db_read.o cbn_zhang2.o hru_lte_read.o pest_washp.o soil_plant_init.o ru_read.o \
	cli_slrgen.o et_pot.o wind_ero_rough.o res_read_init.o cli_precip_control.o sd_hydsed_read.o \
	ru_output.o tillage_data_module.o ch_read_init.o rls_routesoil.o swr_subwq.o mgt_harvtuber.o \
	sim_inityr.o reservoir_output.o calsoft_sum_output.o ch_rtsed_kodatie.o icl.o water_body_module.o \
	jdt.o recall_read.o pest_enrsb.o sq_snom.o hru_output.o solt_db_read.o qman.o hmet_hru_aqu_read.o \
	ch_read.o time_control.o till_parm_read.o res_read_elements.o hru_lte_module.o calsoft_ave_output.o \
	ch_rtsed.o readcio_read.o cli_wndgen.o header_reservoir.o channel_data_module.o \
	mgt_tillfactor.o plant_init.o obj_output.o unit_hyd.o recall_module.o pl_partition.o hyd_connect_out.o \
	plant_all_init.o smp_filter.o output_landscape_module.o landuse_read.o mgt_read_harvops.o \
	recall_output.o theta.o dr_read_path.o soiltest_all_init.o hru_lte_control.o ru_control.o \
	fert_parm_read.o nut_nlch.o proc_allo.o ch_rtsed_bagnold.o cli_initwgn.o header_snutc.o ch_read_hyd.o \
	swr_percmacro.o scen_read_bmpuser.o readtime_read.o cli_tair.o wind_ero_bare.o pl_leaf_drop.o \
	wetland_output.o exco_read_om.o cal_parmchg_read.o hyd_read_connect.o read_mgtops.o proc_read.o \
	ch_watqual.o pest_pesty.o mgt_read_grazeops.o swr_depstor.o proc_open.o swr_substor.o zero2.o \
	ch_rthr.o surface.o res_allo.o ee.o hru_dtbl_actions_init.o rte_read_nut.o NCsed_leach.o \
	field_read.o zero0.o readpcom.o ch_read_elements.o topo_read.o ru_read_elements.o path_ls_process.o \
	header_hyd.o res_read_hyd.o res_hydro.o soil_nutcarb_output.o scen_read_grwway.o pl_read_parms_cal.o \
	exco_read_path.o dr_read_hmet.o swr_satexcess.o hyd_connect.o pl_community.o ch_watqual4.o \
	ch_initial.o soil_nutcarb_init.o ran1.o res_pesticide_output.o ccu_output.o sq_daycn.o ch_watqual2.o \
	om_water_init.o mgt_read_chemapp.o cli_tmeas.o pl_leaf_senes.o sq_canopyint.o calhard_control.o \
	ch_ttcoef.o salt_data_module.o output_ls_pathogen_module.o mgt_newtillmix.o wet_read_hyd.o \
	header_sd_channel.o nut_solp.o lsu_read_elements.o path_ls_swrouting.o pl_read_regions_cal.o \
	conditional_module.o pl_pupd.o cli_tgen.o cli_pmeas.o salt_cha_res_read.o dr_db_read.o \
	sd_hydsed_init.o cli_weatgn.o dtbl_res_read.o mgt_killop.o constituent_mass_module.o cli_pgenhr.o \
	pest_apply.o cal_cond_read.o channel_control.o header_aquifer.o res_objects.o dr_read.o hcsin_output.o \
	pest_decay.o exco_read_hmet.o ch_read_nut.o landuse_data_module.o cal_parm_select.o hru_control.o \
	zeroini.o wind_data_module.o res_nutrient.o urban_parm_read.o time_conc_init.o ch_hhwatqual.o \
	nut_nrain.o climate_module.o ch_rtout.o ls_read_parms_cal.o pl_graze.o header_pest.o \
	ch_read_parms_cal.o ch_rthsed.o mgt_operations_module.o carbon_module.o pl_moisture_gro_init.o \
	dr_read_om.o sq_greenampt.o septic_data_module.o ch_read_orders_cal.o nuts.o swr_drains.o proc_bsn.o \
	hru_module.o rec_read_elements.o pl_mortality.o res_pesticide_module.o re_initialize.o caltsoft_hyd.o \
	ch_rtday.o path_parm_read.o cli_wgnread.o nut_pminrl.o wind_ero_unshelt.o constit_hyd_mult.o \
	hru_soiltest_update.o res_read_sed.o calsoft_hyd.o  pl_nupd.o chg_par.o hru_lte_output.o ru_allo.o \
	ru_module.o pest_parm_read.o rls_routetile.o ero_ovrsed.o proc_res.o swr_latsed.o mgt_read_irrops.o \
	nut_np_flow.o topography_data_module.o res_sediment.o ch_rtpath.o nut_psed.o hru_urb_bmp.o \
	nut_pminrl2.o pest_lch.o proc_cond.o ch_rtmusk.o layersplit.o proc_date_time.o channel_output.o \
	hrudb_init.o caps.o calsoft_plant.o object_read_output.o salt_hru_aqu_read.o res_pest.o sq_volq.o \
	pl_fert.o pesticide_data_module.o xmon.o septic_parm_read.o cal_parm_read.o exco_read.o cli_hmeas.o \
	mgt_read_sweepops.o soil_nutcarb_write.o mgt_operatn.o zero1.o ero_ysed.o hru_output_allo.o \
	topohyd_init.o soils_init.o hydro_init.o hru_pathogen_output.o proc_cal.o hru_urbanhr.o hydrol_read.o \
	fcgd.o stmp_solt.o plant_parm_read.o wind_ero_control.o proc_cha.o hydin_output.o reg_read_elements.o \
	curno.o pl_moisture_senes_init.o output_landscape_init.o et_act.o expo.o header_cs.o nut_nminrl.o \
	pl_dormant.o channel_allo.o sim_initday.o pl_seed_gro.o calibration_data_module.o ch_biofilm.o \
	header_write.o pl_moisture_gro.o soil_phys_init.o flow_dur_curve.o lsreg_output.o est_orfdim.o \
	cli_smeas.o salt_hru_init.o cli_read_atmodep.o conditions.o cal_conditions.o nut_denit.o \
	channel_velocity_module.o exco_read_pest.o swr_origtile.o ch_noqual.o header_path.o sep_biozone.o \
	mgt_harvbiomass.o calsoft_chsed.o sd_channel_output.o smp_grass_wway.o cli_rhgen.o res_read_nut.o \
	pest_hru_aqu_read.o channel_module.o sq_crackflow.o time_module.o ch_rchinit.o pl_nut_demand.o \
	NP_flow.o hru_allo.o pl_root_gro.o soil_module.o ero_eiusle.o ch_read_temp.o ch_rtpest.o \
	est_weirdim.o define_unit_elements.o sep_read.o varinit.o exco_db_read.o hydrology_data_module.o \
	sd_channel_surf_link.o cli_wmeas.o proc_db.o plant_data_module.o hru_read.o nut_orgn.o \
	ch_rtsed_Molinas_Wu.o pl_nup.o pl_waterup.o ch_rchuse.o ttcoef_wway.o stor_surfstor.o \
	mgt_read_fireops.o mgt_plantop.o hcsout_output.o swr_percmain.o header_channel.o wet_initial.o \
	pl_leaf_gro.o soil_db_read.o cli_staread.o plant_module.o ls_link.o ch_pathogen_output.o \
	pest_cha_res_read.o pesticide_init.o scen_read_filtstrip.o erfc.o ran.o plantparm_init.o cli_clgen.o \
	calsoft_sed.o ero_cfactor.o dtbl_lum_read.o command.o smp_bmpfixed.o cons_prac_read.o swr_percmicro.o \
	sd_channel_nutrients.o pl_biomass_gro.o wind_ero_veg.o channel_surf_link.o sd_channel_module.o \
	sq_surfst.o smp_buffer.o path_cha_res_read.o proc_hru.o search.o fertilizer_data_module.o \
	hyddep_output.o cli_atmodep_time_control.o tiles_data_module.o pl_burnop.o sdr_read.o path_ls_runoff.o \
	cli_dstn1.o reservoir_module.o nut_orgnc2.o ch_rtsed_yangsand.o pest_soil_tot.o regres.o \
	wind_ero_erod.o mgt_harvgrain.o organic_mineral_mass_module.o wet_read.o res_read.o pl_pup.o \
	lcu_read_softcal.o structure_set_parms.o ch_hhnoqual.o dtbl_scen_read.o climate_control.o \
	mgt_read_mgtops.o hru_pesticide_output.o output_ls_pesticide_module.o path_apply.o mgt_trop_gro.o \
	ch_read_sed.o pl_moisture_senes.o dr_read_salt.o dr_ru.o sd_chanmorph_output.o ch_pesticide_module.o \
	cntbl_read.o header_wetland.o ch_pathogen_module.o pl_nfix.o pl_rootfr.o header_yield.o \
	sd_channel_read.o pathogen_init.o rls_routesurf.o res_control.o soil_data_module.o \
	cha_pesticide_output.o nut_orgnc.o input_file_module.o cli_pgen.o gcycl.o constit_db_read.o \
	urban_data_module.o res_initial.o cli_bounds_check.o overbank_read.o header_mgt.o pl_tstr.o \
	dr_module.o dr_read_pest.o ch_watqual3.o calsoft_control.o dtbl_flocon_read.o exco_read_salt.o \
	hru_hyds.o hru_sweep.o sq_dailycn.o exco_module.o sq_crackvol.o channel_om_output.o \
	sd_channel_control.o output_ls_salt_module.o maximum_data_module.o

main.o: main.f90
	gfortran -c -ffree-line-length-none main.f90 actions.f90 albedo.f90 allocate_parms.f90 \
	animal_herd_module.f90 aqu2d_init.f90 aqu2d_read.f90 aqu_1d_control.f90 aqu_hyds.f90 aqu_initial.f90 \
	aqu_pesticide_module.f90 aqu_pesticide_output.f90 aqu_read.f90 aqu_read_elements.f90 aqu_read_init.f90 \
	aquifer_module.f90 aquifer_output.f90 ascrv.f90 atri.f90 aunif.f90 basin_aqu_pest_output.f90 \
	basin_aquifer_output.f90 basin_ch_pest_output.f90 basin_chanmorph_output.f90 basin_channel_output.f90 \
	basin_ls_pest_output.f90 basin_module.f90 basin_output.f90 basin_print_codes_read.f90 basin_prm_default.f90 \
	basin_read_cc.f90 basin_read_objs.f90 basin_read_prm.f90 basin_recall_output.f90 basin_res_pest_output.f90 \
	basin_reservoir_output.f90 basin_sdchannel_output.f90 cal_allo_init.f90 ch_watqual_semi_analitical_function.f90 \
	path_hru_aqu_read.f90 hru_urban.f90 overland_n_read.f90 soiltest_init.f90 hydrograph_module.f90 \
	pathogen_data_module.f90 water_hru.f90 nut_nitvol.f90 hydout_output.f90 reservoir_data_module.f90 lsu_output.f90 \
	snowdb_read.f90 res_read_weir.f90 pl_grow.f90 calsoft_read_codes.f90 ero_pkq.f90 mgt_sched.f90 wetland_control.f90 \
	soil_lte_db_read.f90 cbn_zhang2.f90 hru_lte_read.f90 pest_washp.f90 soil_plant_init.f90 ru_read.f90 \
	cli_slrgen.f90 et_pot.f90 wind_ero_rough.f90 res_read_init.f90 cli_precip_control.f90 sd_hydsed_read.f90 \
	ru_output.f90 tillage_data_module.f90 ch_read_init.f90 rls_routesoil.f90 swr_subwq.f90 mgt_harvtuber.f90 \
	sim_inityr.f90 reservoir_output.f90 calsoft_sum_output.f90 ch_rtsed_kodatie.f90 icl.f90 water_body_module.f90 \
	jdt.f90 recall_read.f90 pest_enrsb.f90 sq_snom.f90 hru_output.f90 solt_db_read.f90 qman.f90 hmet_hru_aqu_read.f90 \
	ch_read.f90 time_control.f90 till_parm_read.f90 res_read_elements.f90 hru_lte_module.f90 calsoft_ave_output.f90 \
	ch_rtsed.f90 readcio_read.f90 cli_wndgen.f90 header_reservoir.f90 channel_data_module.f90 \
	mgt_tillfactor.f90 plant_init.f90 obj_output.f90 unit_hyd.f90 recall_module.f90 pl_partition.f90 hyd_connect_out.f90 \
	plant_all_init.f90 smp_filter.f90 output_landscape_module.f90 landuse_read.f90 mgt_read_harvops.f90 \
	recall_output.f90 theta.f90 dr_read_path.f90 soiltest_all_init.f90 hru_lte_control.f90 ru_control.f90 \
	fert_parm_read.f90 nut_nlch.f90 proc_allo.f90 ch_rtsed_bagnold.f90 cli_initwgn.f90 header_snutc.f90 ch_read_hyd.f90 \
	swr_percmacro.f90 scen_read_bmpuser.f90 readtime_read.f90 cli_tair.f90 wind_ero_bare.f90 pl_leaf_drop.f90 \
	wetland_output.f90 exco_read_om.f90 cal_parmchg_read.f90 hyd_read_connect.f90 read_mgtops.f90 proc_read.f90 \
	ch_watqual.f90 pest_pesty.f90 mgt_read_grazeops.f90 swr_depstor.f90 proc_open.f90 swr_substor.f90 zero2.f90 \
	ch_rthr.f90 surface.f90 res_allo.f90 ee.f90 hru_dtbl_actions_init.f90 rte_read_nut.f90 NCsed_leach.f90 \
	field_read.f90 zero0.f90 readpcom.f90 ch_read_elements.f90 topo_read.f90 ru_read_elements.f90 path_ls_process.f90 \
	header_hyd.f90 res_read_hyd.f90 res_hydro.f90 soil_nutcarb_output.f90 scen_read_grwway.f90 pl_read_parms_cal.f90 \
	exco_read_path.f90 dr_read_hmet.f90 swr_satexcess.f90 hyd_connect.f90 pl_community.f90 ch_watqual4.f90 \
	ch_initial.f90 soil_nutcarb_init.f90 ran1.f90 res_pesticide_output.f90 ccu_output.f90 sq_daycn.f90 ch_watqual2.f90 \
	om_water_init.f90 mgt_read_chemapp.f90 cli_tmeas.f90 pl_leaf_senes.f90 sq_canopyint.f90 calhard_control.f90 \
	ch_ttcoef.f90 salt_data_module.f90 output_ls_pathogen_module.f90 mgt_newtillmix.f90 wet_read_hyd.f90 \
	header_sd_channel.f90 nut_solp.f90 lsu_read_elements.f90 path_ls_swrouting.f90 pl_read_regions_cal.f90 \
	conditional_module.f90 pl_pupd.f90 cli_tgen.f90 cli_pmeas.f90 salt_cha_res_read.f90 dr_db_read.f90 \
	sd_hydsed_init.f90 cli_weatgn.f90 dtbl_res_read.f90 mgt_killop.f90 constituent_mass_module.f90 cli_pgenhr.f90 \
	pest_apply.f90 cal_cond_read.f90 channel_control.f90 header_aquifer.f90 res_objects.f90 dr_read.f90 hcsin_output.f90 \
	pest_decay.f90 exco_read_hmet.f90 ch_read_nut.f90 landuse_data_module.f90 cal_parm_select.f90 hru_control.f90 \
	zeroini.f90 wind_data_module.f90 res_nutrient.f90 urban_parm_read.f90 time_conc_init.f90 ch_hhwatqual.f90 \
	nut_nrain.f90 climate_module.f90 ch_rtout.f90 ls_read_parms_cal.f90 pl_graze.f90 header_pest.f90 \
	ch_read_parms_cal.f90 ch_rthsed.f90 mgt_operations_module.f90 carbon_module.f90 pl_moisture_gro_init.f90 \
	dr_read_om.f90 sq_greenampt.f90 septic_data_module.f90 ch_read_orders_cal.f90 nuts.f90 swr_drains.f90 proc_bsn.f90 \
	hru_module.f90 rec_read_elements.f90 pl_mortality.f90 res_pesticide_module.f90 re_initialize.f90 caltsoft_hyd.f90 \
	ch_rtday.f90 path_parm_read.f90 cli_wgnread.f90 nut_pminrl.f90 wind_ero_unshelt.f90 constit_hyd_mult.f90 \
	hru_soiltest_update.f90 res_read_sed.f90 calsoft_hyd.f90  pl_nupd.f90 chg_par.f90 hru_lte_output.f90 ru_allo.f90 \
	ru_module.f90 pest_parm_read.f90 rls_routetile.f90 ero_ovrsed.f90 proc_res.f90 swr_latsed.f90 mgt_read_irrops.f90 \
	nut_np_flow.f90 topography_data_module.f90 res_sediment.f90 ch_rtpath.f90 nut_psed.f90 hru_urb_bmp.f90 \
	nut_pminrl2.f90 pest_lch.f90 proc_cond.f90 ch_rtmusk.f90 layersplit.f90 proc_date_time.f90 channel_output.f90 \
	hrudb_init.f90 caps.f90 calsoft_plant.f90 object_read_output.f90 salt_hru_aqu_read.f90 res_pest.f90 sq_volq.f90 \
	pl_fert.f90 pesticide_data_module.f90 xmon.f90 septic_parm_read.f90 cal_parm_read.f90 exco_read.f90 cli_hmeas.f90 \
	mgt_read_sweepops.f90 soil_nutcarb_write.f90 mgt_operatn.f90 zero1.f90 ero_ysed.f90 hru_output_allo.f90 \
	topohyd_init.f90 soils_init.f90 hydro_init.f90 hru_pathogen_output.f90 proc_cal.f90 hru_urbanhr.f90 hydrol_read.f90 \
	fcgd.f90 stmp_solt.f90 plant_parm_read.f90 wind_ero_control.f90 proc_cha.f90 hydin_output.f90 reg_read_elements.f90 \
	curno.f90 pl_moisture_senes_init.f90 output_landscape_init.f90 et_act.f90 expo.f90 header_cs.f90 nut_nminrl.f90 \
	pl_dormant.f90 channel_allo.f90 sim_initday.f90 pl_seed_gro.f90 calibration_data_module.f90 ch_biofilm.f90 \
	header_write.f90 pl_moisture_gro.f90 soil_phys_init.f90 flow_dur_curve.f90 lsreg_output.f90 est_orfdim.f90 \
	cli_smeas.f90 salt_hru_init.f90 cli_read_atmodep.f90 conditions.f90 cal_conditions.f90 nut_denit.f90 \
	channel_velocity_module.f90 exco_read_pest.f90 swr_origtile.f90 ch_noqual.f90 header_path.f90 sep_biozone.f90 \
	mgt_harvbiomass.f90 calsoft_chsed.f90 sd_channel_output.f90 smp_grass_wway.f90 cli_rhgen.f90 res_read_nut.f90 \
	pest_hru_aqu_read.f90 channel_module.f90 sq_crackflow.f90 time_module.f90 ch_rchinit.f90 pl_nut_demand.f90 \
	NP_flow.F90 hru_allo.f90 pl_root_gro.f90 soil_module.f90 ero_eiusle.f90 ch_read_temp.f90 ch_rtpest.f90 \
	est_weirdim.f90 define_unit_elements.f90 sep_read.f90 varinit.f90 exco_db_read.f90 hydrology_data_module.f90 \
	sd_channel_surf_link.f90 cli_wmeas.f90 proc_db.f90 plant_data_module.f90 hru_read.f90 nut_orgn.f90 \
	ch_rtsed_Molinas_Wu.f90 pl_nup.f90 pl_waterup.f90 ch_rchuse.f90 ttcoef_wway.f90 stor_surfstor.f90 \
	mgt_read_fireops.f90 mgt_plantop.f90 hcsout_output.f90 swr_percmain.f90 header_channel.f90 wet_initial.f90 \
	pl_leaf_gro.f90 soil_db_read.f90 cli_staread.f90 plant_module.f90 ls_link.f90 ch_pathogen_output.f90 \
	pest_cha_res_read.f90 pesticide_init.f90 scen_read_filtstrip.f90 erfc.f90 ran.f90 plantparm_init.f90 cli_clgen.f90 \
	calsoft_sed.f90 ero_cfactor.f90 dtbl_lum_read.f90 command.f90 smp_bmpfixed.f90 cons_prac_read.f90 swr_percmicro.f90 \
	sd_channel_nutrients.f90 pl_biomass_gro.f90 wind_ero_veg.f90 channel_surf_link.f90 sd_channel_module.f90 \
	sq_surfst.f90 smp_buffer.f90 path_cha_res_read.f90 proc_hru.f90 search.f90 fertilizer_data_module.f90 \
	hyddep_output.f90 cli_atmodep_time_control.f90 tiles_data_module.f90 pl_burnop.f90 sdr_read.f90 path_ls_runoff.f90 \
	cli_dstn1.f90 reservoir_module.f90 nut_orgnc2.f90 ch_rtsed_yangsand.f90 pest_soil_tot.f90 regres.f90 \
	wind_ero_erod.f90 mgt_harvgrain.f90 organic_mineral_mass_module.f90 wet_read.f90 res_read.f90 pl_pup.f90 \
	lcu_read_softcal.f90 structure_set_parms.f90 ch_hhnoqual.f90 dtbl_scen_read.f90 climate_control.f90 \
	mgt_read_mgtops.f90 hru_pesticide_output.f90 output_ls_pesticide_module.f90 path_apply.f90 mgt_trop_gro.f90 \
	ch_read_sed.f90 pl_moisture_senes.f90 dr_read_salt.f90 dr_ru.f90 sd_chanmorph_output.f90 ch_pesticide_module.f90 \
	cntbl_read.f90 header_wetland.f90 ch_pathogen_module.f90 pl_nfix.f90 pl_rootfr.f90 header_yield.f90 \
	sd_channel_read.f90 pathogen_init.f90 rls_routesurf.f90 res_control.f90 soil_data_module.f90 \
	cha_pesticide_output.f90 nut_orgnc.f90 input_file_module.f90 cli_pgen.f90 gcycl.f90 constit_db_read.f90 \
	urban_data_module.f90 res_initial.f90 cli_bounds_check.f90 overbank_read.f90 header_mgt.f90 pl_tstr.f90 \
	dr_module.f90 dr_read_pest.f90 ch_watqual3.f90 calsoft_control.f90 dtbl_flocon_read.f90 exco_read_salt.f90 \
	hru_hyds.f90 hru_sweep.f90 sq_dailycn.f90 exco_module.f90 sq_crackvol.f90 channel_om_output.f90 \
	sd_channel_control.f90 output_ls_salt_module.f90 maximum_data_module.f90