name: Compile SAHYSMOD
on:
  push:
    branches:
      - githubActions
jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../src
          cmake --build .
