name: Compile SWAT+
on:
  push:
    branches:
      - githubActions
jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../src
          cmake --build .
          cd ..

      - name: Permissions
        run: chmod +x swatplusTest.sh
        if: runner.os == 'Linux'

      - name: Set up Python for tests
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Poetry for tests
        uses: Gr1N/setup-poetry@v8
      - run: poetry --version

      - name: Test
        run: sh swatplusTest.sh

      - name: Prepare release
        run: mv ./build/bin/swatplus_exe "./dist/SwatPlus-$RUNNER_OS-$TRAVIS_TAG"

      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "dist/SwatPlus-*"
