name: Compile SWAT+
on:
  push:
    branches:
      - githubActions
jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - name: Checkout project

        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          ls
          cd build
          cmake ../src
          cmake --build .
